<<<<<<< HEAD
USE [Multiverse]
GO

/*
	Information for Github Commit
*/


INSERT INTO [dbo].DC VALUES ('Bruce Wayne','Batman','Bat Family');
INSERT INTO [dbo].DC VALUES ('Clark Kent','Superman','House Of El');
INSERT INTO [dbo].DC VALUES ('Diana Price','Wonder Woman','Amazon');
INSERT INTO [dbo].Marvel VALUES ('Tony Stark','Iron Man','Iron Legion');
INSERT INTO [dbo].Marvel VALUES ('Steve Rodgers','Captain America','Project: Rebirth');
INSERT INTO [dbo].Marvel VALUES ('Thor Odinson','Donald Blake','Warrior Three');
INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Harrison Wells', 'Harry Wells' ,'S.T.A.R Labs' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_19 VALUES ('Harrison Wells', 'HR Wells' ,'S.T.A.R Labs' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_16 VALUES ('Harrison Wells', 'Hells Wells' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_17 VALUES ('Harrison Wells', 'Harrison Wells (Earth Seventeen)' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_18 VALUES ('Harrison Wells', 'Harrison Wells (Francophone)' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].[Arrowverse] VALUES ('Oliver Queen', 'Green Arrow', 'Team Arrow', 'Stephen Amell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laurel Lance', 'Black Canary', 'Team Arrow', 'Katie Cassidy');
INSERT INTO [dbo].[Arrowverse] VALUES ('Thea Queen', 'Speedy', 'Team Arrow', 'Willa Holland');
INSERT INTO [dbo].[Arrowverse] VALUES ('Roy Harper', 'Arsenal', 'Team Arrow', 'Colton Haynes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Malcolm Merlyn', 'Dark Archer', 'Legion Of Doom', 'John Barrowman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ray Palmer', 'The Atom', 'Legends', 'Brandon Routh');
INSERT INTO [dbo].[Arrowverse] VALUES ('Curtis Holt', 'Mr Terrific', 'Palmer Technology', 'Echo Kellum');
INSERT INTO [dbo].[Arrowverse] VALUES ('Rene Ramirez', 'Wild Dog', 'United States Navy SEALs', 'Rick Gonzalez');
INSERT INTO [dbo].[Arrowverse] VALUES ('Rory Regan', 'Ragman', 'Team Arrow', 'Joe Dinicol');
INSERT INTO [dbo].[Arrowverse] VALUES ('Evelyn Sharp', 'Artemis', 'Team Prometheus', 'Madison McLaughlin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Dinah Drake', 'Black Canary', 'Star City Police Department', 'Juliana Harkavy');
INSERT INTO [dbo].[Arrowverse] VALUES ('Quentin Lance', 'Detective', 'Star City City Council', 'Paul Blackthorne');
INSERT INTO [dbo].[Arrowverse] VALUES ('Felicity Smoak', 'Overwatch', 'Helix', 'Emily Bett Rickards');
INSERT INTO [dbo].[Arrowverse] VALUES ('Christopher Chance', 'Human Target', 'Solntsevskaya Bratva', 'Wil Traval');
INSERT INTO [dbo].[Arrowverse] VALUES ('John Constantine', '', 'Newcastle Crew', 'Matt Ryan');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Kara Danvers', 'Supergirl', 'House Of El', 'Melissa Benoist');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ted Grant', 'Wildcat', 'Wildcat Gym', 'J.R. Ramirez');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mari McCabe', 'Vixen', '', 'Megalyn Echikunwoke');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tatsu Yamashiro', 'Katana', 'Crescent Order', 'Rila Fukushima');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mesi Natifah', 'Talibah', 'League of Assassins', 'Natasha Gayle');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lyla Michaels', 'Harbinger', 'A.R.G.U.S.', 'Audrey Marie Anderson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Anatoly Knyazev', 'KGBeast', 'Solntsevskaya Bratva', 'David Nykl');
INSERT INTO [dbo].[Arrowverse] VALUES ('Nyssa Raatko', 'Nyssa Al Ghul', 'League of Assassins', 'Katrina Law');
INSERT INTO [dbo].[Arrowverse] VALUES ('Slade Wilson', 'Deathstroke', 'Church of Blood', 'Manu Bennett');
INSERT INTO [dbo].[Arrowverse] VALUES ('John Diggle Junior', 'Green Arrow', 'Team Arrow (2046)', 'Joseph David-Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Esrin Fortuna', '', '', 'Gabriella Wright');
INSERT INTO [dbo].[Arrowverse] VALUES ('Susan Williams', '', 'Channel 52', 'Carly Pope');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cindy', 'Sin', '', 'Bex Taylor-Klaus');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alena', 'Kojo Sledgehammer', 'Helix', 'Kacey Rohl');
INSERT INTO [dbo].[Arrowverse] VALUES ('Andy Diggle', 'The Ghost', ' H.I.V.E.', 'Eugene Byrd');
INSERT INTO [dbo].[Arrowverse] VALUES ('Digger Harkness', 'Captain Boomerang', 'Task Force X', 'Nick E. Tarabay');
INSERT INTO [dbo].[Arrowverse] VALUES ('Noah Kuttler', 'The Calculator', '', 'Tom Amandes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alexi Leonov', '', 'Solntsevskaya Bratva', 'Eugene Lipinski');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lonnie Machin', 'Anarky', '', 'Alexander Calvert');
INSERT INTO [dbo].[Arrowverse] VALUES ('Billy Malone', 'Detective Malone', 'Star City Police Department', 'Tyler Ritter');
INSERT INTO [dbo].[Arrowverse] VALUES ('Amanda Waller', 'Mockingbird', 'A.R.G.U.S.', 'Cynthia Addai-Robinson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cecil Adams', 'Count Vertigo', 'Vertigo', 'Seth Gabel');
INSERT INTO [dbo].[Arrowverse] VALUES ('Helena Bertinelli', 'The Huntress', 'La Morte Sussurrata', 'Jessica De Gouw');
INSERT INTO [dbo].[Arrowverse] VALUES ('Roy G. Bivolo', 'Rainbow Raider', '', 'Paul Anthony');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tobias Church', 'Charon', 'Church Gang', 'Chad L. Coleman');
INSERT INTO [dbo].[Arrowverse] VALUES ('James Edlund', '', '', 'Cliff Chamberlain');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joseph Falk', 'The Savior', 'Starling City Department of Transportation', 'Christopher Redman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Simon Lacroix', 'Komodo', '', 'Matt Ward');
INSERT INTO [dbo].[Arrowverse] VALUES ('Brie Larvan', 'Bug-Eyed Bandit', 'Mercury Labs', 'Emily Kinney');
INSERT INTO [dbo].[Arrowverse] VALUES ('Garfield Lynns', 'The Firefly', 'Starling City Fire Department', 'Andrew Dunbar');
INSERT INTO [dbo].[Arrowverse] VALUES ('Barton Mathis', 'The Dollmaker', '', 'Michael Eklund');
INSERT INTO [dbo].[Arrowverse] VALUES ('Xavier Reed', 'The Mayor', 'Mayor Gang', 'Clé Bennett');
INSERT INTO [dbo].[Arrowverse] VALUES ('Derek Sampson', 'Stardust', 'Stardust Gang', 'Cody Runnels');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hath-Set', 'Vandal Savage', 'Kasnia Conglomerate', 'Casper Crump');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mark Scheffer', 'Shrapnel', 'Suicide Squad', 'Sean Maher');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jake Simmons', 'Deathbolt', '', 'Doug Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Smith', 'Glasses', 'National Security Agency', 'Donnelly Rhodes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Sean Sonus', 'Discord', '', 'Steve Bacic');
INSERT INTO [dbo].[Arrowverse] VALUES ('Isaac Stanzler', 'Vengeance', '', 'Nathan Mitchell');
INSERT INTO [dbo].[Arrowverse] VALUES ('William Tockman', 'Clock King', 'Kord Industries', 'Robert Knepper');
INSERT INTO [dbo].[Arrowverse] VALUES ('J.G. Walker', 'General Walker', 'U.S. Army', 'Garry Chalk');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laura Washington', 'Cyber-woman', '', 'Erica Luttrell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Dr. Webb', 'Count Vertigo', 'Starling City Mental Institution', 'Darren Dolynski');
INSERT INTO [dbo].[Arrowverse] VALUES ('Grant Wilson', 'Deathstroke', '', 'Jamie Andrew Cutler');
INSERT INTO [dbo].[Arrowverse] VALUES ('Werner Zytle', 'Vertigo', 'Vertigo Gang', 'Peter Stormare');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mr. Blank', '', '', 'J. August Richards');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Scimitar', 'Church Gang', 'Curtis Braconnier');
INSERT INTO [dbo].[Arrowverse] VALUES ('Liza Warner', 'Lady Cop', 'Lady Team', 'Rutina Wesley');
INSERT INTO [dbo].[Arrowverse] VALUES ('Chien Na Wei', 'China White', 'Chinese Triad', 'Kelly Hu');
INSERT INTO [dbo].[Arrowverse] VALUES ('Carrie Cutter', 'Cupid', 'Suicide Squad', 'Amy Gumenick');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ted Gaynor', '', 'Blackhawk Squad Protection Group', 'Ben Browder');
INSERT INTO [dbo].[Arrowverse] VALUES ('Blake', '', 'Blackhawk Squad Protection Group', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cavanaugh', '', 'Blackhawk Squad Protection Group', 'Jae Lee');
INSERT INTO [dbo].[Arrowverse] VALUES ('Paul Knox', '', 'Blackhawk Squad Protection Group', 'Colin Lawrence');
INSERT INTO [dbo].[Arrowverse] VALUES ('Sebastian Blood', 'Brother Blood', 'Church of Blood', 'Kevin Alejandro');
INSERT INTO [dbo].[Arrowverse] VALUES ('Daily', 'The Masked Man', 'Church of Blood', 'Jesse Hutch');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cyrus Gold', 'The Acolyte', 'Church of Blood', 'Graham Shiels');
INSERT INTO [dbo].[Arrowverse] VALUES ('Caleb Green', '', 'Church of Blood', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Clinton Hogue', 'Brother Blood', 'Church of Blood', 'Roark Critchlow');
INSERT INTO [dbo].[Arrowverse] VALUES ('Isabel Rochev', 'Ravager', 'Church of Blood', 'Summer Glau');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hoshaw Tolibao', 'Brother Hoshaw', 'Church of Blood', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Ripped', 'Church of Blood', 'Garfield Wilson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ruvé Adams', 'Ruvé Darhk', 'H.I.V.E.', 'Janet Kidder');
INSERT INTO [dbo].[Arrowverse] VALUES ('Michael Amar', 'Murmur', 'H.I.V.E.', 'Adrian Glynn McMorran');
INSERT INTO [dbo].[Arrowverse] VALUES ('Milo Armitage', '', 'H.I.V.E.', 'James Kidnie');
INSERT INTO [dbo].[Arrowverse] VALUES ('Phaedra Nixon', '', 'H.I.V.E.', 'Lynda Boyd');
INSERT INTO [dbo].[Arrowverse] VALUES ('Danny Brickwell', 'Brick', 'H.I.V.E.', 'Vinnie Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alex Davis', '', 'H.I.V.E.', 'Parker Young');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mina Fayad', '', 'H.I.V.E.', 'Carmen Moore');
INSERT INTO [dbo].[Arrowverse] VALUES ('Floyd Lawton', 'Deadshot', 'Suicide Squad', 'Michael Rowe');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cooper Seldon', '', 'Brother Eye', 'Nolan Gerard Funk');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mark Shaw', 'Manhunter', 'A.R.G.U.S.', 'David Cubitt');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jeremy Tell', 'Double Down', 'H.I.V.E.', 'JR Bourne');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ben Turner', 'Bronze Tiger', 'Suicide Squad', 'Michael Jai White');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Rosie', 'Demolition Team', 'Rachel Luttrell');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Hardhat', 'Demolition Team', 'Marc Trottier');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Jackhammer', 'Demolition Team', 'Daniel Cudmore');
INSERT INTO [dbo].[Arrowverse] VALUES ('Aglin', '', 'The Hoods', 'Derek Hamilton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Baker', '', 'The Hoods', 'Doug Chapman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Colton', '', 'The Hoods', 'Giacomo Baessato');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jeff Deveau', '', 'The Hoods', 'Jason Griffith');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Ras al Ghul', 'League of Assassins', 'Matt Nable');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Al-Owal', 'League of Assassins', 'Navid Negahban');
INSERT INTO [dbo].[Arrowverse] VALUES ('Chase', '', 'Verdant', 'Austin Butler');
INSERT INTO [dbo].[Arrowverse] VALUES ('Maseo Yamashiro', 'Sarab', 'League of Assassins', 'Karl Yune');
INSERT INTO [dbo].[Arrowverse] VALUES ('Winnick Norton', 'The Dodger', 'Renegades', 'James Callis');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lyle Bolton', '', 'Renegades', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Bartek Kuranski', '', 'Renegades', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cyrus Vanch', '', 'Renegades', 'David Anders');
INSERT INTO [dbo].[Arrowverse] VALUES ('Derek Reston', 'King', 'Royal Flush Gang ', 'Currie Graham');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kyle Reston', 'Ace', 'Royal Flush Gang ', 'Kyle Schmid');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mrs. Reston', '', 'Royal Flush Gang ', 'Sarah-Jane Redmond');
INSERT INTO [dbo].[Arrowverse] VALUES ('Teddy Reston', 'Jack', 'Royal Flush Gang ', 'Tom Stevens');
INSERT INTO [dbo].[Arrowverse] VALUES ('Baron Reiter', '', 'Shadowspire', 'Jimmy Akingbola');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kenny', '', 'Shadowspire', 'Jae Lee');
INSERT INTO [dbo].[Arrowverse] VALUES ('Conklin', '', 'Shadowspire', 'Ryan Robbins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joyner', '', 'Shadowspire', 'Erik Palladino');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eric Dunn', 'Lead Skull', 'Spooky Crew', 'Toby Levins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laura Buser', 'Bonesy', 'Spooky Crew', 'Tirra Dent');
INSERT INTO [dbo].[Arrowverse] VALUES ('Simon Morrison', 'Prometheus', 'Team Prometheus', 'Josh Segarra');
INSERT INTO [dbo].[Arrowverse] VALUES ('Talia al Ghul', '', 'Talia al Ghul cult', 'Lexa Doig');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Vigilante', 'Star City Trust Bank', 'Mick Wingert');
INSERT INTO [dbo].[Arrowverse] VALUES ('Samantha Clayton', '', '', 'Anna Hopkins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Barry Allen', 'The Flash', 'Team Flash', 'Grant Gustin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cisco Ramon', 'Vibe', 'S.T.A.R. Labs', 'Carlos Valdes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Caitlin Snow', 'Killer Frost', 'S.T.A.R. Labs', 'Danielle Panabaker');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eobard Thawne', 'Reverse-Flash', 'Legion of Doom', 'Matt Letscher');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joe West', '', 'Central City Police  Department', 'Jesse L. Martin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Henry Allen', '', 'Team Flash', 'John Wesley Shipp');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ronnie Raymond', 'Firestorm', 'S.T.A.R. Labs', 'Robbie Amell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Martin Stein', 'Firestorm', 'Legends', 'Victor Garber');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eddie Thawne', '', 'Central City Police Department', 'Rick Cosnett');
INSERT INTO [dbo].[Arrowverse] VALUES ('Iris West', '', 'Central City Picture News', 'Candice Patton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Wally West', 'Kid Flash', 'Team Flash', 'Keiynan Lonsdale');
INSERT INTO [dbo].[Arrowverse] VALUES ('Julian Albert', 'Alchemy', 'Central City Police Department', 'Tom Felton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tracy Brand', '', 'Central City University', 'Anne Dudek');
INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Hunter Zolomon', 'Black Flash', 'Speed Force', 'Teddy Sears');
INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Jesse Chambers-Wells', 'Jesse Quick', 'Team Flash', 'Violett Beane');
INSERT INTO [dbo].[Arrowverse_Earth_3] VALUES ('Jay Garrick', 'The Flash', '', 'John Wesley Shipp');
INSERT INTO [dbo].[Arrowverse] VALUES ('Frankie Kane', 'Magenta', '', 'Joey King');
INSERT INTO [dbo].[Arrowverse] VALUES ('Christina McGee', '', 'Mercury Labs', 'Amanda Pays');
INSERT INTO [dbo].[Arrowverse] VALUES ('Linda Park', '', 'Central City Picture News', 'Malese Jow');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hartley Rathaway', 'Pied Piper', 'S.T.A.R. Labs', 'Andy Mientus');
INSERT INTO [dbo].[Arrowverse] VALUES ('Clarissa Stein', '', '', 'Isabella Hofmann');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lily Stein', '', 'Massachusetts Institute of Technology', 'Christina Brucato');
INSERT INTO [dbo].[Arrowverse] VALUES ('Nate Heywood', 'Steel', 'Legends', 'Nick Zano');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mick Rory', 'Heat Wave', 'Legends', 'Dominic Purcell');
INSERT INTO [dbo].[Arrowverse_Earth_19] VALUES ('', 'Gypsy', 'Collectors', 'Jessica Camacho');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Bartholomew Allen', '', 'Central City Police Department', 'Grant Gustin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Carter Hall', 'Hawkman', 'Legends', 'Falk Hentschel');
INSERT INTO [dbo].[Arrowverse] VALUES ('Scythian Torvil', 'Hawkman', 'Legends', 'Falk Hentschel');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kendra Saunders', 'Hawkgirl', 'Legends', 'Ciara Renée');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kendra', '', '', 'Ciara Renée');
INSERT INTO [dbo].[Arrowverse] VALUES ('Rip Hunter', 'Gareeb', 'Time Masters', 'Arthur Darvill');
INSERT INTO [dbo].[Arrowverse] VALUES ('Bette Sans Souci', 'Plastique', 'Explosive Ordnance Disposal', 'Kelly Frye');
INSERT INTO [dbo].[Arrowverse] VALUES ('Leonard Snart', 'Captain Cold', 'Legends', 'Wentworth Miller');
INSERT INTO [dbo].[Arrowverse] VALUES ('Caitlin Snow', 'Killer Frost', ' Zoom', 'Danielle Panabaker');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lisa Snart', 'Golden Glider', '', 'Peyton List');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Iris West-Allen', 'Detective West', 'Central City Police Department ', 'Candice Patton');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Laurel Lance', 'Black Siren', 'Team Prometheus', 'Katie Cassidy');
INSERT INTO [dbo].[Arrowverse] VALUES ('Shawna Baez', 'Peek-a-Boo', '', 'Britne Oldford');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kyle Nimbus', 'The Mist', 'Darbinyan crime family', 'Anthony Carrigan');
INSERT INTO [dbo].[Arrowverse] VALUES ('Barry Allen', 'Savitar', 'Cult of Savitar', 'Grant Gustin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Craig', 'Acolyte', 'Cult of Savitar', 'Blair Penner');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hannibal Bates', 'Everyman', '', 'Martin Novotny');
INSERT INTO [dbo].[Arrowverse] VALUES ('Danton Black', 'Multiplex', 'Stagg Industries', 'Michael Christopher Smith');
INSERT INTO [dbo].[Arrowverse] VALUES ('Edward Clariss', 'The Rival', '', 'Todd Lasance');
INSERT INTO [dbo].[Arrowverse] VALUES ('Wade Eiling', 'Goldfinger', 'U.S. Army', 'Clancy Brown');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Robert Queen', 'The Arrow', '', '');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Oliver Queen', '', '', '');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Shay Lamden', 'King Shark', 'A.R.G.U.S.', 'David Hayter');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Linda Park', 'Dr. Light', '', 'Malese Jow');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Francisco Ramon', 'Reverb', 'Zooms meta-human group', 'Carlos Valdes');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Dante Ramon', 'Rupture', 'Zooms meta-human group', 'Nicholas Gonzalez');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Ronnie Raymond', 'Deathstorm', 'Zooms meta-human group', 'Robbie Amell');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Martin Stein', 'Deathstorm', 'Zooms meta-human group', '');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Adam Fells', 'Geomancer', '', '');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Evan McCulloch', 'Mirror Master', '', '');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Eddie Slick', 'Sand Demon', '', 'Kett Turton');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Al Rothstein', 'Atom-Smasher', '', 'Adam Copeland');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Solovar', '', 'Gorilla City', 'Keith David');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Floyd Lawton', 'Deadshot', 'Central City Police Department ', 'Michael Rowe');
INSERT INTO [dbo].[Arrowverse_Earth_2] VALUES ('Henry Hewitt', '', 'S.T.A.R. Labs', 'Demore Barnes');
INSERT INTO [dbo].[Flash1990] VALUES ('Barry Allen', 'The Flash', 'Central City Police', 'John Wesley Shipp');
INSERT INTO [dbo].[Flash1990] VALUES ('Christina McGee', 'S.T.A.R. Labs', 'S.T.A.R. Labs', 'Amanda Pays');
INSERT INTO [dbo].[Flash1990] VALUES ('Alex Desert', '', 'Central City Police', 'Julio Mendez');
INSERT INTO [dbo].[Flash1990] VALUES ('Leonard Wynters', 'Captain Cold', '', 'Micheal Champion');
INSERT INTO [dbo].[Flash1990] VALUES ('James Jesse', 'The Trickster', '', 'Mark Hamill');
INSERT INTO [dbo].[Flash1990] VALUES ('Barry Allen', 'Pollux', '', 'John Wesley Shipp');
INSERT INTO [dbo].[Flash1990] VALUES ('Desmond Powell', 'Nightshade', 'Central City Hospital', 'Jason Bernard');
INSERT INTO [dbo].[Flash1990] VALUES ('Joe Kline', '', 'WCCN TV', 'Richard Belzer');
INSERT INTO [dbo].[Flash1990] VALUES ('Tony Bellows', '', 'Central City Police', 'Vito D Ambrosio');
INSERT INTO [dbo].[Flash1990] VALUES ('Michael Francis Murphy', '', 'Central City Police', 'Biff Manard');
INSERT INTO [dbo].[Flash1990] VALUES ('Warren Garfield', '', 'Central City Police', 'Mike Genovese');
INSERT INTO [dbo].[Flash1990] VALUES ('Megan Lockhart', 'Prank', '', 'Joyce Hyser');
INSERT INTO [dbo].[Flash1990] VALUES ('Zoey Clark', 'Prank', '', 'Corinne Bohrer');
INSERT INTO [dbo].[Flash1990] VALUES ('Henry Allen', '', 'Central City Police', 'M. Emmet Walsh ');
INSERT INTO [dbo].[Flash1990] VALUES ('Fosnight', '', '', 'Dick Miller');
INSERT INTO [dbo].[Flash1990] VALUES ('Nora Allen', '', '', 'Priscilla Pointer');
INSERT INTO [dbo].[Flash1990] VALUES ('Sabrina', '', '', 'Gloria Reuben');
INSERT INTO [dbo].[Flash1990] VALUES ('Reg', 'Reg the News Stand Vendor', '', 'Robert Shayne');
INSERT INTO [dbo].[Flash1990] VALUES ('Nicholas Pike', '', 'Dark Riders', 'Michael Nader');
INSERT INTO [dbo].[Flash1990] VALUES ('Curtis Bohannan', 'Deadly Nightshade', '', 'Richard Burgi');
INSERT INTO [dbo].[Flash1990] VALUES ('Sam Scudder', 'Mirror Master', '', 'David Cassidy');
INSERT INTO [dbo].[Flash1990] VALUES ('Jimmy Swain', '', '', 'Jeffrey Combs');
INSERT INTO [dbo].[Flash1990] VALUES ('Dr. Rebecca Frost:', '', '', 'Denise Crosby');
INSERT INTO [dbo].[Flash1990] VALUES ('Iris West', '', '', 'Paula Marshall');
INSERT INTO [dbo].[Flash1990] VALUES ('Roger Braintree', '', '', 'Bill Mumy');
INSERT INTO [dbo].[Flash1990] VALUES ('Belle Crocker', 'The Ghostess', '', 'Lois Nettleton');
INSERT INTO [dbo].[Flash1990] VALUES ('Felicia Kane', '', '', 'Jeri Ryan');
INSERT INTO [dbo].[Flash1990] VALUES ('Russell', 'The Ghost', '', 'Anthony Starke');
INSERT INTO [dbo].[Flash1990] VALUES ('Jay Allen', '', 'Central City Police', 'Tim Thomerson');
INSERT INTO [dbo].[Flash1990] VALUES ('Linda Park', '', 'Central City News', 'Mariko Tse');
INSERT INTO [dbo].[Flash1990] VALUES ('Terry Cohan', '', '', 'Jonathan Brandis');
INSERT INTO [dbo].[Flash1990] VALUES ('Phillip Moses', '', '', 'Bryan Cranston');
INSERT INTO [dbo].[Flash1990] VALUES ('Osako', '', '', ' Mark Dacascos');
INSERT INTO [dbo].[Flash1990] VALUES ('Victor Kelso', '', '', 'Robert OReilly');
INSERT INTO [dbo].[Flash1990] VALUES ('', 'Omega', '', 'Sven-Ole Thorsen');
INSERT INTO [dbo].[Arrowverse_Earth_3] VALUES ('', 'The Trickster', '', 'Mark Hamill');
INSERT INTO dbo.Watchmen VALUES('Nelson Gardner', 'Captain Metropolis', 'Minutemen','Darryl Scheeelar');
INSERT INTO dbo.Watchmen VALUES('Edward Blake', 'The Comedian', 'U.S. Government','Jeffery Dean Morgan');
INSERT INTO dbo.Watchmen VALUES('', 'Hooded Justice', 'Minutemen','Glenn Ennis');
INSERT INTO dbo.Watchmen VALUES('Hollis Mason', 'Nite Owl', 'New York Police Department','Steven McHattie');
INSERT INTO dbo.Watchmen VALUES('Ursula Zandt', 'Silhouette', 'Minutemen','Apollonia Vanova');
INSERT INTO dbo.Watchmen VALUES('Sally Jupiter', 'Silk Spectre', 'Minutemen','Carla Cugino');
INSERT INTO dbo.Watchmen VALUES('William Brady', 'Dollar Bill', 'National Bank','Dan Payne');
INSERT INTO dbo.Watchmen VALUES('Byron Lewis', 'Mothman', 'Minutemen','Niall Matter');
INSERT INTO dbo.Watchmen VALUES('Dan Dreiberg', 'Nite Owl', 'Watchmen','Patrick Wilson');
INSERT INTO dbo.Watchmen VALUES('Jon Osterman', 'Dr Manhattan', 'Rockefeller Military Research Centre','Billy Crudup');
INSERT INTO dbo.Watchmen VALUES('Walter Kovacs', 'Rorschach', 'Watchmen','Jackie Earle Haley');
INSERT INTO dbo.Watchmen VALUES('Laurie Juspeczyk', 'Silk Spectre', 'Minutemen','Malin Akerman');
INSERT INTO dbo.Watchmen VALUES('Adrian Veidt', 'Ozymandias', 'Veidt Enterprises','Matthew Goode');
INSERT INTO dbo.Kingsman VALUES('Gary Unwin', 'Galahad', 'Kingsman','Taron Egerton');
INSERT INTO dbo.Kingsman VALUES('Harry Hart', 'Galahad', 'Kingsman','Colin Firth');
INSERT INTO dbo.Kingsman VALUES('Chester King', 'Arthur', 'Kingsman','Michael Caine');
INSERT INTO dbo.Kingsman VALUES('James Spencer', 'Lancelot', 'Kingsman','Jack Davenport');
INSERT INTO dbo.Kingsman VALUES('Roxanne Morton', 'Lancelot', 'Kingsman','Sophie Cookson');
INSERT INTO dbo.Kingsman VALUES('', 'Merlin', 'Kingsman','Mark Strong');
INSERT INTO dbo.Kingsman VALUES('Lee Unwin', '', 'Kingsman','Jonno Davies');
INSERT INTO dbo.Kingsman VALUES('Richmond Valentine', '', 'Valentine Corporation','Samuel L Jackson');
INSERT INTO dbo.Kingsman VALUES('', 'Champagne', 'Statesman','Jeff Bridges');
INSERT INTO dbo.Kingsman VALUES('', 'Ginger Ale', 'Statesman','Halle Berry');
INSERT INTO dbo.Kingsman VALUES('', 'Tequila', 'Statesman','Channing Tatum');
INSERT INTO dbo.Kingsman VALUES('Jack Daniels', 'Whiskey', 'Statesman','Pedro Pascal');
INSERT INTO dbo.Kingsman VALUES('Gazelle', '', 'Valentine Corporation','Sofia Boutella');
INSERT INTO dbo.Kingsman VALUES('Michelle Unwin', '', '','Samantha Womack');
INSERT INTO dbo.Kingsman VALUES('Dean Baker', '', '','Geoff Ball');
INSERT INTO dbo.Kingsman VALUES('Charlie Hesketh', '', 'The Golden Circle','Edward Holcroft');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Jimmy Olsen', 'Guardian', 'CatCo Worldwide Media', 'Mehcad Brooks');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Winn Schott Jr', ' Man in the Van', 'Department of Extra-Normal Operations', 'Jeremy Jordan');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Catherine Grant', 'The Queen of all Media', 'CatCo Worldwide Media', 'Calista Flockart');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Jeremiah Danvers', '', 'D.E.O', 'Dean Cain');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Eliza Danvers', '', '', 'Helen Slater');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Clark Kent', 'Superman', 'House Of El', 'Tyler Hoechlin');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Alura Zor-El', '', 'House Of El', 'Erica Durance');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Astra', '', 'Astra/Non Army', 'Laura Benanti');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Maxwell Lord', '', 'Lord Technologies', 'Peter Facinelli');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Lucy Lane', '', 'Judge Advocate Generals Group', 'Jenna Dewan-Tatum');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Hank Henshaw', 'Cyborg-Superman', 'Project: Cadmus', 'David Harewood');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Non', '', 'Astra/Non Army', 'Chris Vance');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Zor-El', '', 'House Of El', 'Robert Gant');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Jane Doe', 'Bizarro', 'Lord Technologies', 'Hope Lauren');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Siobhan Smythe', 'Silver Banshee', '', 'Italia Ricci');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Brainiac 8', 'Indigo', 'Astra/Non Army', 'Laura Vandervoort');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Sam Lane', '', 'U.S. Army', 'Glen Morshower');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Mon-El', 'Mark Matthews', 'Daxam Monarchy', 'Chris Wood');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('', 'Oliva Marsdin', 'United States of America', 'Linda Carter');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Lar Gand', '', 'Daxam Monarchy', 'Kevin Sorbo');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Rhea', '', 'Daxam Monarchy', 'Teri Hatcher');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Snapper Carr', '', 'CatCo Worldwide Media', 'Ian Gomez');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Lena Luthor', '', 'L-Corp', 'Katie McGrath');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Lillian Luthor', 'The Doctor', 'Project: Cadmus', 'Brenda Strong');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Eve Teschmacher', '', 'CatCo Worldwide Media', 'Andrea Brooks');
INSERT INTO [dbo].Supergirl_Earth_38 VALUES ('Mgann Morzz', 'Miss Martian', '', 'Sharon Leal');
INSERT INTO [dbo].DC VALUES ('Carter Hall', 'Hawkman', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Jay Garrick', 'The Flash', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Alan Scott', 'Green Lantern', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Ted Grant', 'Wildcat', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Jim Corrigan', 'The Spectre', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Sylvester Pemberton', 'Star Spangled Kid', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Al Pratt', 'The Atom', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Wesley Dodds', 'Sandman', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Rex Tyler', 'Hourman', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Charles McNider', 'Dr Mid-Nite', 'Justice Society Of America');
INSERT INTO [dbo].DC VALUES ('Jefferson Pierce', 'Black Lightning', 'Outsiders');
INSERT INTO [dbo].DC VALUES ('Dan Garrett', 'Blue Beetle', 'Midwestern University');
INSERT INTO [dbo].DC VALUES ('Ted Kord', 'Blue Beetle', 'Kord Industries');
INSERT INTO [dbo].DC VALUES ('Jamie Reyes', 'Blue Beetle', 'Teen Titans');
INSERT INTO [dbo].DC VALUES ('John Stewart', 'Green Lantern', 'United States Marine Corp');
INSERT INTO [dbo].DC VALUES ('Guy Gardener', 'Green Lantern', 'Justice League International');
INSERT INTO [dbo].DC VALUES ('Kyle Rayner', 'Green Lantern', 'New Guardians');
INSERT INTO [dbo].DC VALUES ('Jessica Cruz', 'Green Lantern', 'Green Lantern Corps');
INSERT INTO [dbo].DC VALUES ('Simon Baz', 'Green Lantern', 'Green Lantern Corps');
INSERT INTO [dbo].DC VALUES ('Abin Sur', 'Green Lantern', 'Green Lantern Corps');

SELECT * FROM dbo.DC;
SELECT * FROM dbo.Marvel;
SELECT * FROM dbo.Arrowverse;
SELECT * FROM dbo.Arrowverse_Earth_16;
SELECT * FROM dbo.Arrowverse_Earth_17;
SELECT * FROM dbo.Arrowverse_Earth_18;
SELECT * FROM dbo.Arrowverse_Earth_19;
SELECT * FROM dbo.Arrowverse_Earth_2;
SELECT * FROM dbo.Arrowverse_Earth_3;
SELECT * FROM dbo.Supergirl_Earth_38;
SELECT * FROM dbo.Flash1990;
SELECT * FROM dbo.Watchmen;
SELECT * FROM dbo.Kingsman;
=======
USE [Multiverse]
GO

/*
	Information for Github Commit
*/

INSERT INTO [dbo].DC
	VALUES
           ('Bruce Wayne','Batman','Bat Family','Ben Affleck'),
           ('Clark Kent','Superman','House Of El','Tyler Hoechlin'),
           ('Diana Price','Wonder Woman','Amazon','Gal Gadot');

INSERT INTO [dbo].Marvel
     VALUES
           ('Tony Stark','Iron Man','Iron Legion','Robert Downey Jr'),
           ('Steve Rodgers','Captain America','Project: Rebirth','Chris Evans'),
           ('Thor Odinson','Donald Blake','Warrior Three','Chris Hemsworth');



USE [Multiverse]
GO


INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Harrison Wells', 'Harry Wells' ,'S.T.A.R Labs' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_19 VALUES ('Harrison Wells', 'HR Wells' ,'S.T.A.R Labs' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_16 VALUES ('Harrison Wells', 'Hells Wells' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_17 VALUES ('Harrison Wells', 'Harrison Wells (Earth Seventeen)' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].Arrowverse_Earth_18 VALUES ('Harrison Wells', 'Harrison Wells (Francophone)' ,'' ,'Tom Cavanagh');
INSERT INTO [dbo].[Arrowverse] VALUES ('Oliver Queen', 'Green Arrow', 'Team Arrow', 'Stephen Amell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laurel Lance', 'Black Canary', 'Team Arrow', 'Katie Cassidy');
INSERT INTO [dbo].[Arrowverse] VALUES ('Thea Queen', 'Speedy', 'Team Arrow', 'Willa Holland');
INSERT INTO [dbo].[Arrowverse] VALUES ('Roy Harper', 'Arsenal', 'Team Arrow', 'Colton Haynes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Malcolm Merlyn', 'Dark Archer', 'Legion Of Doom', 'John Barrowman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ray Palmer', 'The Atom', 'Legends', 'Brandon Routh');
INSERT INTO [dbo].[Arrowverse] VALUES ('Curtis Holt', 'Mr Terrific', 'Palmer Technology', 'Echo Kellum');
INSERT INTO [dbo].[Arrowverse] VALUES ('Rene Ramirez', 'Wild Dog', 'United States Navy SEALs', 'Rick Gonzalez');
INSERT INTO [dbo].[Arrowverse] VALUES ('Rory Regan', 'Ragman', 'Team Arrow', 'Joe Dinicol');
INSERT INTO [dbo].[Arrowverse] VALUES ('Evelyn Sharp', 'Artemis', 'Team Prometheus', 'Madison McLaughlin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Dinah Drake', 'Black Canary', 'Star City Police Department', 'Juliana Harkavy');
INSERT INTO [dbo].[Arrowverse] VALUES ('Quentin Lance', 'Detective', 'Star City City Council', 'Paul Blackthorne');
INSERT INTO [dbo].[Arrowverse] VALUES ('Felicity Smoak', 'Overwatch', 'Helix', 'Emily Bett Rickards');
INSERT INTO [dbo].[Arrowverse] VALUES ('Christopher Chance', 'Human Target', 'Solntsevskaya Bratva', 'Wil Traval');
INSERT INTO [dbo].[Arrowverse] VALUES ('John Constantine', '', 'Newcastle Crew', 'Matt Ryan');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kara Danvers', 'Supergirl', 'House Of El', 'Melissa Benoist');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ted Grant', 'Wildcat', 'Wildcat Gym', 'J.R. Ramirez');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mari McCabe', 'Vixen', '', 'Megalyn Echikunwoke');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tatsu Yamashiro', 'Katana', 'Crescent Order', 'Rila Fukushima');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mesi Natifah', 'Talibah', 'League of Assassins', 'Natasha Gayle');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lyla Michaels', 'Harbinger', 'A.R.G.U.S.', 'Audrey Marie Anderson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Anatoly Knyazev', 'KGBeast', 'Solntsevskaya Bratva', 'David Nykl');
INSERT INTO [dbo].[Arrowverse] VALUES ('Nyssa Raatko', 'Nyssa Al Ghul', 'League of Assassins', 'Katrina Law');
INSERT INTO [dbo].[Arrowverse] VALUES ('Slade Wilson', 'Deathstroke', 'Church of Blood', 'Manu Bennett');
INSERT INTO [dbo].[Arrowverse] VALUES ('John Diggle Junior', 'Green Arrow', 'Team Arrow (2046)', 'Joseph David-Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Esrin Fortuna', '', '', 'Gabriella Wright');
INSERT INTO [dbo].[Arrowverse] VALUES ('Susan Williams', '', 'Channel 52', 'Carly Pope');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cindy', 'Sin', '', 'Bex Taylor-Klaus');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alena', 'Kojo Sledgehammer', 'Helix', 'Kacey Rohl');
INSERT INTO [dbo].[Arrowverse] VALUES ('Andy Diggle', 'The Ghost', ' H.I.V.E.', 'Eugene Byrd');
INSERT INTO [dbo].[Arrowverse] VALUES ('Digger Harkness', 'Captain Boomerang', 'Task Force X', 'Nick E. Tarabay');
INSERT INTO [dbo].[Arrowverse] VALUES ('Noah Kuttler', 'The Calculator', '', 'Tom Amandes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alexi Leonov', '', 'Solntsevskaya Bratva', 'Eugene Lipinski');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lonnie Machin', 'Anarky', '', 'Alexander Calvert');
INSERT INTO [dbo].[Arrowverse] VALUES ('Billy Malone', 'Detective Malone', 'Star City Police Department', 'Tyler Ritter');
INSERT INTO [dbo].[Arrowverse] VALUES ('Amanda Waller', 'Mockingbird', 'A.R.G.U.S.', 'Cynthia Addai-Robinson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cecil Adams', 'Count Vertigo', 'Vertigo', 'Seth Gabel');
INSERT INTO [dbo].[Arrowverse] VALUES ('Helena Bertinelli', 'The Huntress', 'La Morte Sussurrata', 'Jessica De Gouw');
INSERT INTO [dbo].[Arrowverse] VALUES ('Roy G. Bivolo', 'Rainbow Raider', '', 'Paul Anthony');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tobias Church', 'Charon', 'Church Gang', 'Chad L. Coleman');
INSERT INTO [dbo].[Arrowverse] VALUES ('James Edlund', '', '', 'Cliff Chamberlain');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joseph Falk', 'The Savior', 'Starling City Department of Transportation', 'Christopher Redman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Simon Lacroix', 'Komodo', '', 'Matt Ward');
INSERT INTO [dbo].[Arrowverse] VALUES ('Brie Larvan', 'Bug-Eyed Bandit', 'Mercury Labs', 'Emily Kinney');
INSERT INTO [dbo].[Arrowverse] VALUES ('Garfield Lynns', 'The Firefly', 'Starling City Fire Department', 'Andrew Dunbar');
INSERT INTO [dbo].[Arrowverse] VALUES ('Barton Mathis', 'The Dollmaker', '', 'Michael Eklund');
INSERT INTO [dbo].[Arrowverse] VALUES ('Xavier Reed', 'The Mayor', 'Mayor Gang', 'Clé Bennett');
INSERT INTO [dbo].[Arrowverse] VALUES ('Derek Sampson', 'Stardust', 'Stardust Gang', 'Cody Runnels');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hath-Set', 'Vandal Savage', 'Kasnia Conglomerate', 'Casper Crump');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mark Scheffer', 'Shrapnel', 'Suicide Squad', 'Sean Maher');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jake Simmons', 'Deathbolt', '', 'Doug Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Smith', 'Glasses', 'National Security Agency', 'Donnelly Rhodes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Sean Sonus', 'Discord', '', 'Steve Bacic');
INSERT INTO [dbo].[Arrowverse] VALUES ('Isaac Stanzler', 'Vengeance', '', 'Nathan Mitchell');
INSERT INTO [dbo].[Arrowverse] VALUES ('William Tockman', 'Clock King', 'Kord Industries', 'Robert Knepper');
INSERT INTO [dbo].[Arrowverse] VALUES ('J.G. Walker', 'General Walker', 'U.S. Army', 'Garry Chalk');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laura Washington', 'Cyber-woman', '', 'Erica Luttrell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Dr. Webb', 'Count Vertigo', 'Starling City Mental Institution', 'Darren Dolynski');
INSERT INTO [dbo].[Arrowverse] VALUES ('Grant Wilson', 'Deathstroke', '', 'Jamie Andrew Cutler');
INSERT INTO [dbo].[Arrowverse] VALUES ('Werner Zytle', 'Vertigo', 'Vertigo Gang', 'Peter Stormare');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mr. Blank', '', '', 'J. August Richards');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Scimitar', 'Church Gang', 'Curtis Braconnier');
INSERT INTO [dbo].[Arrowverse] VALUES ('Liza Warner', 'Lady Cop', 'Lady Team', 'Rutina Wesley');
INSERT INTO [dbo].[Arrowverse] VALUES ('Chien Na Wei', 'China White', 'Chinese Triad', 'Kelly Hu');
INSERT INTO [dbo].[Arrowverse] VALUES ('Carrie Cutter', 'Cupid', 'Suicide Squad', 'Amy Gumenick');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ted Gaynor', '', 'Blackhawk Squad Protection Group', 'Ben Browder');
INSERT INTO [dbo].[Arrowverse] VALUES ('Blake', '', 'Blackhawk Squad Protection Group', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cavanaugh', '', 'Blackhawk Squad Protection Group', 'Jae Lee');
INSERT INTO [dbo].[Arrowverse] VALUES ('Paul Knox', '', 'Blackhawk Squad Protection Group', 'Colin Lawrence');
INSERT INTO [dbo].[Arrowverse] VALUES ('Sebastian Blood', 'Brother Blood', 'Church of Blood', 'Kevin Alejandro');
INSERT INTO [dbo].[Arrowverse] VALUES ('Daily', 'The Masked Man', 'Church of Blood', 'Jesse Hutch');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cyrus Gold', 'The Acolyte', 'Church of Blood', 'Graham Shiels');
INSERT INTO [dbo].[Arrowverse] VALUES ('Caleb Green', '', 'Church of Blood', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Clinton Hogue', 'Brother Blood', 'Church of Blood', 'Roark Critchlow');
INSERT INTO [dbo].[Arrowverse] VALUES ('Isabel Rochev', 'Ravager', 'Church of Blood', 'Summer Glau');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hoshaw Tolibao', 'Brother Hoshaw', 'Church of Blood', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Ripped', 'Church of Blood', 'Garfield Wilson');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ruvé Adams', 'Ruvé Darhk', 'H.I.V.E.', 'Janet Kidder');
INSERT INTO [dbo].[Arrowverse] VALUES ('Michael Amar', 'Murmur', 'H.I.V.E.', 'Adrian Glynn McMorran');
INSERT INTO [dbo].[Arrowverse] VALUES ('Milo Armitage', '', 'H.I.V.E.', 'James Kidnie');
INSERT INTO [dbo].[Arrowverse] VALUES ('Phaedra Nixon', '', 'H.I.V.E.', 'Lynda Boyd');
INSERT INTO [dbo].[Arrowverse] VALUES ('Danny Brickwell', 'Brick', 'H.I.V.E.', 'Vinnie Jones');
INSERT INTO [dbo].[Arrowverse] VALUES ('Alex Davis', '', 'H.I.V.E.', 'Parker Young');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mina Fayad', '', 'H.I.V.E.', 'Carmen Moore');
INSERT INTO [dbo].[Arrowverse] VALUES ('Floyd Lawton', 'Deadshot', 'Suicide Squad', 'Michael Rowe');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cooper Seldon', '', 'Brother Eye', 'Nolan Gerard Funk');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mark Shaw', 'Manhunter', 'A.R.G.U.S.', 'David Cubitt');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jeremy Tell', 'Double Down', 'H.I.V.E.', 'JR Bourne');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ben Turner', 'Bronze Tiger', 'Suicide Squad', 'Michael Jai White');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Rosie', 'Demolition Team', 'Rachel Luttrell');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Hardhat', 'Demolition Team', 'Marc Trottier');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Jackhammer', 'Demolition Team', 'Daniel Cudmore');
INSERT INTO [dbo].[Arrowverse] VALUES ('Aglin', '', 'The Hoods', 'Derek Hamilton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Baker', '', 'The Hoods', 'Doug Chapman');
INSERT INTO [dbo].[Arrowverse] VALUES ('Colton', '', 'The Hoods', 'Giacomo Baessato');
INSERT INTO [dbo].[Arrowverse] VALUES ('Jeff Deveau', '', 'The Hoods', 'Jason Griffith');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Ras al Ghul', 'League of Assassins', 'Matt Nable');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Al-Owal', 'League of Assassins', 'Navid Negahban');
INSERT INTO [dbo].[Arrowverse] VALUES ('Chase', '', 'Verdant', 'Austin Butler');
INSERT INTO [dbo].[Arrowverse] VALUES ('Maseo Yamashiro', 'Sarab', 'League of Assassins', 'Karl Yune');
INSERT INTO [dbo].[Arrowverse] VALUES ('Winnick Norton', 'The Dodger', 'Renegades', 'James Callis');
INSERT INTO [dbo].[Arrowverse] VALUES ('Lyle Bolton', '', 'Renegades', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Bartek Kuranski', '', 'Renegades', '');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cyrus Vanch', '', 'Renegades', 'David Anders');
INSERT INTO [dbo].[Arrowverse] VALUES ('Derek Reston', 'King', 'Royal Flush Gang ', 'Currie Graham');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kyle Reston', 'Ace', 'Royal Flush Gang ', 'Kyle Schmid');
INSERT INTO [dbo].[Arrowverse] VALUES ('Mrs. Reston', '', 'Royal Flush Gang ', 'Sarah-Jane Redmond');
INSERT INTO [dbo].[Arrowverse] VALUES ('Teddy Reston', 'Jack', 'Royal Flush Gang ', 'Tom Stevens');
INSERT INTO [dbo].[Arrowverse] VALUES ('Baron Reiter', '', 'Shadowspire', 'Jimmy Akingbola');
INSERT INTO [dbo].[Arrowverse] VALUES ('Kenny', '', 'Shadowspire', 'Jae Lee');
INSERT INTO [dbo].[Arrowverse] VALUES ('Conklin', '', 'Shadowspire', 'Ryan Robbins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joyner', '', 'Shadowspire', 'Erik Palladino');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eric Dunn', 'Lead Skull', 'Spooky Crew', 'Toby Levins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Laura Buser', 'Bonesy', 'Spooky Crew', 'Tirra Dent');
INSERT INTO [dbo].[Arrowverse] VALUES ('Simon Morrison', 'Prometheus', 'Team Prometheus', 'Josh Segarra');
INSERT INTO [dbo].[Arrowverse] VALUES ('Talia al Ghul', '', 'Talia al Ghul cult', 'Lexa Doig');
INSERT INTO [dbo].[Arrowverse] VALUES ('', 'Vigilante', 'Star City Trust Bank', 'Mick Wingert');
INSERT INTO [dbo].[Arrowverse] VALUES ('Samantha Clayton', '', '', 'Anna Hopkins');
INSERT INTO [dbo].[Arrowverse] VALUES ('Barry Allen', 'The Flash', 'Team Flash', 'Grant Gustin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Cisco Ramon', 'Vibe', 'S.T.A.R. Labs', 'Carlos Valdes');
INSERT INTO [dbo].[Arrowverse] VALUES ('Caitlin Snow', 'Killer Frost', 'S.T.A.R. Labs', 'Danielle Panabaker');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eobard Thawne', 'Reverse-Flash', 'Legion of Doom', 'Matt Letscher');
INSERT INTO [dbo].[Arrowverse] VALUES ('Joe West', '', 'Central City Police  Department', 'Jesse L. Martin');
INSERT INTO [dbo].[Arrowverse] VALUES ('Henry Allen', '', 'Team Flash', 'John Wesley Shipp');
INSERT INTO [dbo].[Arrowverse] VALUES ('Ronnie Raymond', 'Firestorm', 'S.T.A.R. Labs', 'Robbie Amell');
INSERT INTO [dbo].[Arrowverse] VALUES ('Martin Stein', 'Firestorm', 'Legends', 'Victor Garber');
INSERT INTO [dbo].[Arrowverse] VALUES ('Eddie Thawne', '', 'Central City Police Department', 'Rick Cosnett');
INSERT INTO [dbo].[Arrowverse] VALUES ('Iris West', '', 'Central City Picture News', 'Candice Patton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Wally West', 'Kid Flash', 'Team Flash', 'Keiynan Lonsdale');
INSERT INTO [dbo].[Arrowverse] VALUES ('Julian Albert', 'Alchemy', 'Central City Police Department', 'Tom Felton');
INSERT INTO [dbo].[Arrowverse] VALUES ('Tracy Brand', '', 'Central City University', 'Anne Dudek');
INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Hunter Zolomon', 'Black Flash', 'Speed Force', 'Teddy Sears');
INSERT INTO [dbo].Arrowverse_Earth_2 VALUES ('Jesse Chambers-Wells', 'Jesse Quick', 'Team Flash', 'Violett Beane');
INSERT INTO [dbo].[Arrowverse_Earth_3] VALUES ('Jay Garrick', 'The Flash', '', 'John Wesley Shipp');
INSERT INTO [dbo].[Arrowverse] VALUES ('Frankie Kane', 'Magenta', '', 'Joey King');
INSERT INTO [dbo].[Arrowverse] VALUES ('Christina McGee', '', 'Mercury Labs', 'Amanda Pays');
INSERT INTO [dbo].[Arrowverse] VALUES ('Linda Park', '', 'Central City Picture News', 'Malese Jow');
INSERT INTO [dbo].[Arrowverse] VALUES ('Hartley Rathaway', 'Pied Piper', 'S.T.A.R. Labs', 'Andy Mientus');

SELECT * FROM dbo.DC;
SELECT * FROM dbo.Marvel;
>>>>>>> origin/master
